### ISSUE TITLE
stack trace is lost from the point the code uses p-map

### ISSUE THREAD

**Issue by davidfirst** [sindresorhus/p-map#34]
Both, `console.trace` and `throw new Error` don't show the stack-trace beyond the point p-map got called. In other words, the functions that called before pMap, disappear from the stack trace. 
As a comparison, the p-map-series doesn't suffer from this issue. It does keep the stack-trace.

See the example below, if you run a function that runs the native `Promise.all`, the stack trace shows the function name - `runPromiseNative`. Same if you run the function `runPromisePmapSeries`. However, try to run `runPromisePmap`, and you'll see how the stack trace truncated. 

I tried node v12.x and v14.x.

```
const pMap = require('p-map');

const pMapSeries = require('p-map-series');

async function promiseFn() {
  throw new Error('stop')
}

async function runPromiseNative() {
  await Promise.all([promiseFn()]).then(() => { console.log('completed') }).catch((err) => console.error(err));
}

async function runPromisePmap() {
  await pMap([promiseFn], fn => fn()).then(() => { console.log('completed') }).catch((err) => console.error(err));
}

async function runPromisePmapSeries() {
  await pMapSeries([promiseFn], fn => fn()).then(() => { console.log('completed') }).catch((err) => console.error(err));
}

// runPromiseNative();

runPromisePmap();

// runPromisePmapSeries();
```

Results when running `runPromisePmap` :

```
Error: stop
    at fn1 (/Users/davidfirst/teambit/bit/pmap.js:4:9)
    at /Users/davidfirst/teambit/bit/pmap.js:27:27
    at /Users/davidfirst/teambit/bit/node_modules/p-map/index.js:57:28
```

Results when running `runPromiseNative`.
```
Error: stop
    at fn1 (/Users/davidfirst/teambit/bit/pmap.js:4:9)
    at fn2 (/Users/davidfirst/teambit/bit/pmap.js:9:9)
    at fn3 (/Users/davidfirst/teambit/bit/pmap.js:13:9)
    at runPromiseNative (/Users/davidfirst/teambit/bit/pmap.js:23:22)
    at Object.<anonymous> (/Users/davidfirst/teambit/bit/pmap.js:26:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
```

**Comment by sindresorhus** [comment]
This is, unfortunately, a limitation of JavaScript: https://stackoverflow.com/questions/56644392/passing-an-async-function-as-a-callback-causes-the-error-stack-trace-to-be-lost

The only way to solve this is to:
1.  Find a way to refactor `p-map` to not use `new Promise()`. I think the stack trace is preserved if all the async is chained.
2. Or get the stack trace before the await, then afterward, merge the stack traces somehow. We did something like this in Got: https://github.com/sindresorhus/got/blob/462bc630015064fa4ad4358cf28d24f95e1c958b/source/core/index.ts#L1225-L1237

**Comment by davidfirst** [comment]
Thanks @sindresorhus .
I was trying to come up with a different implementation that don't involve the `new Promise` as you suggested, it seems to be working, but the `stopOnError` is not implemented. 
For my use-case I don't need the `stopOnError`, so I guess I'll use it, I'm pasting here just in case you'll find it useful. 

```
module.exports = async (
	iterable,
	mapper,
	{
		concurrency = Infinity,
		stopOnError = true
	} = {}
) => {
	const results = [];
	const iterator = iterable[Symbol.iterator]();
	let completed = false;
	const runBatch = async () => {
		const items = [];
		for (let i = 0; i < concurrency; i++) {
			const iterableResult = iterator.next();
			if (iterableResult.done) {
				completed = true;
				break;
			}
			items.push(iterableResult.value);
		}
		const batchResults = await Promise.all(items.map(item => mapper(item)));
		results.push(...batchResults);
		if (!completed) await runBatch();
	};
	await runBatch();

	return results;
}
```

**Comment by yjpa7145** [comment]
I looked into this a little bit this morning. Running @davidfirst's examples, I'm able to see the short and long stacktraces. From @sindresorhus's comment, I would have expected that the problem was being caused because we were catching the error on line 59, then passing it to `reject`.

I created a simplified version of the `pMap` function to try to replicate this, but I get a full stack trace instead:

```js
const fakepmap = async (f) => {
  return new Promise((resolve, reject) => {

    const next = () => {
      (async () => {
        try {
          resolve(await f());
        } catch (error) {
          reject(error);
        }
      })();
    };

    next();
  });
}

const promiseFn = async () => {
  throw new Error('stop');
};

fakepmap(promiseFn).then(console.log).catch(console.log);

// Error: stop
//     at promiseFn (/Users/me/Source/test.js:19:9)
//     at /Users/me/Source/test.js:7:25
//     at next (/Users/me/Source/test.js:11:9)
//     at /Users/me/Source/test.js:14:5
//     at new Promise (<anonymous>)
//     at fakepmap (/Users/me/Source/test.js:2:10)
//     at Object.<anonymous> (/Users/me/Source/test.js:22:1)
//     at Module._compile (internal/modules/cjs/loader.js:1138:30)
//     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
//     at Module.load (internal/modules/cjs/loader.js:986:32)
```

Any idea what is missing from this test scenario but is present in `pMap` that would cause the different stack output?

**Comment by septatrix** [comment]
> Any idea what is missing from this test scenario but is present in `pMap` that would cause the different stack output?

I do not know the exact thing but your implementation does not limit the concurrency, maybe that could be an issue. It would be really great to have proper stack traces but so far I have not encountered anything which properly solves this so I assume your implementation omits some step which loses the stack trace but is required for limiting the concurrency.

You could also take a look at p-limit. Its code is a decent bit shorter but suffers from the same issue. It might be easier to figure out which step exactly loses the stack trace in that implementation.

**Comment by davidfirst** [comment]
@septatrix, 
> but your implementation does not limit the concurrency

Why do you think so?

**Comment by septatrix** [comment]
> > but your implementation does not limit the concurrency
> 
> Why do you think so?

My answer was in response to the snippet from @marchuffnagle, not yours

**Comment by davidfirst** [comment]
> > > but your implementation does not limit the concurrency
> > 
> > 
> > Why do you think so?
> 
> My answer was in response to the snippet from @marchuffnagle, not yours

Oh sorry, I missed that.

**Comment by davidfirst** [comment]
In case you already have `lodash` in your project, consider this simplified version which also fixes the stack-trace.
```
import { chunk } from 'lodash';

export async function pMapPool<T, X>(
  iterable: T[],
  mapper: (item: T) => Promise<X>,
  {
    concurrency = Infinity
  } = {}
) {
  if (concurrency === Infinity) {
    return Promise.all(iterable.map((item) => mapper(item)));
  }

  const results: X[] = [];
  const chunks = chunk(iterable, concurrency);

  for (const currentChunk of chunks) {
    const batchResults = await Promise.all(currentChunk.map((item) => mapper(item)));
    results.push(...batchResults);
  }

  return results;
}
```
